import random
print("Welcome to Mad Libs!Please choose the number to pick the story:")
print("1. The Hospital,")
print("2. The Camping,")
print("3. The Castle in an Enchanted Forest.")
print("4. Surprise Me!")

choice = input("Please,enter 1, 2, 3 or 4 in order to pick the story!")
if choice == "4":
    choice = str(random.randint(1, 3))
    print(f" The computer chose story number {choice}")
elif choice == "1":
    print("You chose 'The Hospital' story!")
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
    hospital.words_append(input(""))
elif choice == "2"(""))
    print("You chose 'The Camping' story!")
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
    camping.words_append(input(""))
elif choice == "3":
    print("You chose 'The Castle in an Enchanted Forest' story!")
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
    castle.words_append(imput(""))
else:
    print("Invalid choice!Please restart!")
